### ISSUE TITLE
Teleport error infomation

### ISSUE THREAD

**Issue by williambacteria** [masagameplay/MaSuiteCore#13]
My game's name is Nick . When I use /tpa to a player named William , My screen shows "Teleportation request to William" , but William's screen shows "Teleportation request sent to William". I used the rewrite version.

**Comment by chrismwiggs** [comment]
Had the same problem, but seems to have been fixed in https://github.com/masagameplay/MaSuiteTeleports/commit/c71caa7bde3c41617da97a867e3685d4b486089b 

Try rewrite build [#29](https://ci.codemc.io/job/masagameplay/job/MaSuiteTeleports%20Rewrite/29/artifact/target/MaSuiteTeleports.jar) and make sure you restart all your servers, including the proxy if you're using one!

**Comment by williambacteria** [comment]
Thank you very much,I will try it later!
